name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish npm & PyPI packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests & validation
        run: npm run prepublishOnly

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build PyPI distribution
        working-directory: packages/adaptive-tests-py
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m build

      - name: Publish to PyPI
        working-directory: packages/adaptive-tests-py
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*
